apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/grpc-backend: "true"
  name: backend-ingress
spec:
  rules:
    - host: nginx.example.com # cambiar esta linea por su dominio
      http:
        paths:
          - backend:
              serviceName: backend-service
              servicePort: 80
