apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: backend-ingress
spec:
  rules:
    - host: nginx.back.example.com # cambiar esta linea por su dominio
      http:
        paths:
          - backend:
              serviceName: service-back-proyecto-sopes2
              servicePort: 3100
